const express = require('express')
const app = express()
const api = require('./route')
const cors = require('cors')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/api',api)
app.listen(3000,()=>{console.log('阳光彩虹小白马,开始监听中...')})